# Generated by Django 2.2.16 on 2020-09-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ayat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.IntegerField()),
                ('nama_surat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Murottal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.CharField(max_length=100)),
                ('ayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murottal.Ayat')),
                ('qory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murottal.Qory')),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murottal.Surat')),
            ],
        ),
        migrations.AddField(
            model_name='ayat',
            name='surat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murottal.Surat'),
        ),
    ]
